# Generated by Django 5.1.2 on 2025-10-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_student_semester_data_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='package_unit',
            field=models.CharField(choices=[('LPA', 'LPA'), ('K', 'K')], default='LPA', max_length=3),
        ),
        migrations.AlterField(
            model_name='placement',
            name='package',
            field=models.FloatField(default=0.0, help_text='Enter numeric value only'),
        ),
    ]
