# Generated by Django 5.1.2 on 2025-10-23 13:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_placement_package_unit_alter_placement_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
