# Generated by Django 5.2.8 on 2025-11-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_placement_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='current_semester',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
